### ISSUE TITLE
Errores con archivo book_bot.py

### ISSUE THREAD

**Issue by dtejedavilleda** [PythonDayMX/Crea_un_Twitterbot_en_30_minutos#1]
Buenos días. Quiero felicitarte por tu trabajo.
Excelente.
Cuando quiero ejecutar el archivo book_bot.py me muestra los siguientes errores:

C:\Python36-32\Twitterbot_en_30-master\Full>py book_bot.py
Al llegar aquí, sin saber por qué, levantó la cabeza y sus ojos se encontraron con los de su admirador.
Traceback (most recent call last):
  File "book_bot.py", line 69, in <module>
    bot.update_status(status)
  File "C:\Python36-32\lib\site-packages\tweepy\api.py", line 194, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "C:\Python36-32\lib\site-packages\tweepy\binder.py", line 241, in _call
    method = APIMethod(args, kwargs)
  File "C:\Python36-32\lib\site-packages\tweepy\binder.py", line 60, in __init__
    self.build_parameters(args, kwargs)
  File "C:\Python36-32\lib\site-packages\tweepy\binder.py", line 95, in build_parameters
    self.session.params[self.allowed_param[idx]] = convert_to_utf8_str(arg)
  File "C:\Python36-32\lib\site-packages\tweepy\utils.py", line 34, in convert_to_utf8_str
    arg = arg.encode('utf-8')
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 13-14: surrogates not allowed

Sistema operativo windows 10 32 bits
Python 3.6.3
Tweepy instalado

Por favor me puedes ayudar? De anticipado mil gracias.

**Comment by dtejedavilleda** [comment]
versión de tweepy 3.5.0
